# Generated by Django 5.2.4 on 2025-07-23 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(help_text='Ex: 1ère année, 2ème année', max_length=20, verbose_name='Niveau')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2024-2025', max_length=9, verbose_name='Année scolaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True, verbose_name='Numéro étudiant')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, verbose_name='Étudiant actif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code matière')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)], verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Matière active')),
                ('enseignant', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Enseignants'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=2, verbose_name='Semestre')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne générale')),
                ('rang', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang')),
                ('effectif_classe', models.PositiveIntegerField(blank=True, null=True, verbose_name='Effectif classe')),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation générale')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-date_generation'],
                'unique_together': {('etudiant', 'semestre', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note')),
                ('note_sur', models.DecimalField(decimal_places=2, default=20.0, max_digits=4, verbose_name='Note sur')),
                ('type_evaluation', models.CharField(choices=[('DS', 'Devoir Surveillé'), ('CC', 'Contrôle Continu'), ('EX', 'Examen'), ('TP', 'Travaux Pratiques'), ('OR', 'Oral')], default='DS', max_length=2, verbose_name="Type d'évaluation")),
                ('date_evaluation', models.DateField(verbose_name="Date d'évaluation")),
                ('semestre', models.CharField(help_text='S1, S2', max_length=2, verbose_name='Semestre')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.etudiant', verbose_name='Étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.matiere', verbose_name='Matière')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_evaluation'],
                'unique_together': {('etudiant', 'matiere', 'type_evaluation', 'date_evaluation')},
            },
        ),
    ]
