# Generated by Django 5.2.4 on 2025-07-24 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matiere',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant'),
        ),
    ]
